---
- name: Install Prometheus
  become: yes
  apt:
    name: prometheus
    state: present

- name: Copy Prometheus configuration
  template:
    src: roles/prometheus/template/prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
  notify: restart prometheus

- name: Start Prometheus
  service:
    name: prometheus
    state: started
    enabled: yes

- name: Ensure Prometheus starts on boot
  systemd:
    name: prometheus
    enabled: yes

